### ISSUE TITLE
custom Mongo Query resulting in 500 error

### ISSUE THREAD

**Issue by ayunas** [ayunas/geeks-4-geeks#1]
When I try to get Users by age, I'm coming up with a 500 error.  

Custom query is here : mongo/src/main/java/com/geeks4geeks/spring/mongo/user/iUserRepo.java.

**Comment by piyush5807** [comment]
one curl brace is missing in your query Amir, 
the query you have written is 
@Query("{ age : {$gt : ?0, $lt : ?1}")

you have not ended the first open curly brace

the correct one should be - @Query("{ age : {$gt : ?0, $lt : ?1}}")

**Comment by ayunas** [comment]
@piyush5807 Thanks for catching that 👍
